Traceback (most recent call last):
  File "/usr/share/miniconda/envs/blog/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/share/miniconda/envs/blog/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda/envs/blog/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/share/miniconda/envs/blog/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/share/miniconda/envs/blog/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/share/miniconda/envs/blog/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda/envs/blog/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/share/miniconda/envs/blog/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import warnings

import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import plotly.io as pio
import ubicenter
from plotly.subplots import make_subplots

cdfs = pd.read_csv("data/cdfs.csv")
ubi_summary = pd.read_csv("data/ubi_summary.csv")
nw_quant = pd.read_csv("data/deciles.csv")


# Define UBI Center colors
BLUE = "#1976D2"
DARK_BLUE = "#1565C0"
LIGHT_BLUE = "#90CAF9"
GRAY = "#BDBDBD"
DARK_GRAY = "#616161"
BARELY_BLUE = "#E3F2FD"

colors = [BLUE, DARK_BLUE, LIGHT_BLUE, GRAY, BARELY_BLUE]

bl = ubi_summary.iloc[0].round(-2)
params = pd.DataFrame(
    {
        "Mean": {
            "White": bl.white_mean_networth_pa,
            "Black": bl.black_mean_networth_pa,
        },
        "Median": {
            "White": bl.white_median_networth_pa,
            "Black": bl.black_median_networth_pa,
        },
    }
)

fig = go.Figure(
    data=[
        go.Bar(name="White", x=params.T.index, y=params.T["White"], marker_color=GRAY),
        go.Bar(name="Black", x=params.T.index, y=params.T["Black"], marker_color=BLUE),
    ]
)

fig.update_layout(
    title="Traditional measures of the racial wealth gap",
    hovermode="x",
    xaxis_title="",
    yaxis_title="Wealth per adult (2019)",
    yaxis_tickprefix="$",
    legend=dict(yanchor="top", y=0.99, xanchor="left", x=0.75),
)

ubicenter.format_fig(fig)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[0;32m<ipython-input-1-7182eef8b972>[0m in [0;36m<module>[0;34m[0m
[1;32m      6[0m [0;32mimport[0m [0mplotly[0m[0;34m.[0m[0mgraph_objects[0m [0;32mas[0m [0mgo[0m[0;34m[0m[0;34m[0m[0m
[1;32m      7[0m [0;32mimport[0m [0mplotly[0m[0;34m.[0m[0mio[0m [0;32mas[0m [0mpio[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 8[0;31m [0;32mimport[0m [0mubicenter[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      9[0m [0;32mfrom[0m [0mplotly[0m[0;34m.[0m[0msubplots[0m [0;32mimport[0m [0mmake_subplots[0m[0;34m[0m[0;34m[0m[0m
[1;32m     10[0m [0;34m[0m[0m

[0;31mModuleNotFoundError[0m: No module named 'ubicenter'
ModuleNotFoundError: No module named 'ubicenter'

